In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=np.array(50)
print(arr)

50


In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.ndim)
arr.shape=(4,3)
a=arr.reshape(6,2)
print(arr)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [33]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3
(3, 2, 3)


In [29]:
a=np.array((1,2,3),dtype=float)
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [51]:
a=np.arange(20)
b=a.reshape(2,10)
print(a)
print(a.ndim)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [55]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)
x=np.array([1,2,3],dtype=np.float64)
print(x.itemsize)

1
8


In [60]:
a=np.empty((3,3),dtype=int)
print(a)

[[94905883252788              0              0]
 [             0              0              0]
 [             0              0              0]]


In [61]:
x = np.zeros(5)
print(x)

x = np.zeros((6,3), dtype = int)
print(x)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [63]:
x = np.ones(5)
print(x)

x = np.ones((6,3), dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [66]:
x=([1,2,3],[4,5,6])
a=np.asarray(x)
print(a)
y=[(1,2,3),(4,5,6)]
b=np.asarray(y)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [69]:
s = b"hello world"
np.frombuffer(s, dtype='S1', count=5, offset=0)

array([b'h', b'e', b'l', b'l', b'o'], dtype='|S1')

In [72]:
mylist=(x*x for x in range(6))
x=np.fromiter(mylist,dtype=int)
print(x)

[ 0  1  4  9 16 25]


In [89]:
iteration=((x+1,x+2,x+3,x+4) for x in range(6))
x=np.fromiter(iteration,dtype=np.dtype((int,4)))
print(x)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [ ]:
arr=np.array([1,2,3,4])
print(arr[0]+arr[4])