<a href="https://colab.research.google.com/github/fayezkareem/DEPI/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr=np.array(50)
print(arr)

50


In [5]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.ndim)
arr.shape=(4,3)
a=arr.reshape(6,2)
print(arr)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3
(3, 2, 3)


In [8]:
a=np.array((1,2,3),dtype=float)
print(a)
print(type(a))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [9]:
a=np.arange(20)
b=a.reshape(2,10)
print(a)
print(a.ndim)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
1
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [10]:
x=np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)
x=np.array([1,2,3],dtype=np.float64)
print(x.itemsize)

1
8


In [11]:
a=np.empty((3,3),dtype=int)
print(a)

[[96000066762219              0              0]
 [             0              0              0]
 [             0              0              0]]


In [12]:
x = np.zeros(5)
print(x)

x = np.zeros((6,3), dtype = int)
print(x)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
x = np.ones(5)
print(x)

x = np.ones((6,3), dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
x=([1,2,3],[4,5,6])
a=np.asarray(x)
print(a)
y=[(1,2,3),(4,5,6)]
b=np.asarray(y)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [15]:
s = b"hello world"
np.frombuffer(s, dtype='S1', count=5, offset=0)

array([b'h', b'e', b'l', b'l', b'o'], dtype='|S1')

In [16]:
mylist=(x*x for x in range(6))
x=np.fromiter(mylist,dtype=int)
print(x)

[ 0  1  4  9 16 25]


In [17]:
iteration=((x+1,x+2,x+3,x+4) for x in range(6))
x=np.fromiter(iteration,dtype=np.dtype((int,4)))
print(x)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [18]:
arr=np.array([1,2,3,4])
print(arr[0]+arr[3])

5


In [19]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,10,11]]])
print('1st element in row 2=',arr[0,1,1])
print(arr[1,1,-2])

1st element in row 2= 5
10


In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])
print(arr[:4])
print(arr[1:])
print(arr[0:8:2])
print(arr[-3:-1])
print(arr[::4])

[2 3 4 5]
[1 2 3 4]
[2 3 4 5 6 7 8 9]
[1 3 5 7]
[7 8]
[1 5 9]


In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [22]:
arr = np.array(['apple', 'banana', 'orange'])
print(arr)
print(arr.dtype)
arr = np.array([1, 0, 3, 4], dtype='f8')
print(arr.dtype)
print(arr)
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)
arr_new = arr.astype(np.int32)
print(arr_new.dtype)
print(arr_new)


['apple' 'banana' 'orange']
<U6
float64
[1. 0. 3. 4.]
[ True False  True  True]
bool
int32
[1 0 3 4]


In [23]:
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()
arr[0]=50
print(arr)
print(x)
print(y)
print(x.base)
print(y.base)

[50  2  3  4]
[1 2 3 4]
[50  2  3  4]
None
[50  2  3  4]


In [24]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=x.reshape(4,3)
print(newarr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
newarr = arr.flatten()
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [25]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
  print(x)
for x in arr:
  for y in x:
    print(y)

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


In [26]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)
print(x.shape)
for x in np.nditer(arr):
    print(x)
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
for x in np.nditer(arr[:,:, ::2]):
  print(x)
for idx,x in np.ndenumerate(arr):
  print(idx,x)

1
2
3
4
5
6
7
8
9
10
11
12
(2, 3)
1
2
3
4
5
6
7
8
9
10
11
12
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
1
3
4
6
7
9
10
12
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print("#####"*20)
print(arr2)
print("#####"*20)
arr = np.concatenate((arr1, arr2) , axis=1)
print(arr)
print("#####"*20)
arr = np.stack((arr1, arr2), axis=0)
print(arr)
print("#####"*20)
arr = np.hstack((arr1, arr2))
print(arr)
print("#####"*20)
arr = np.vstack((arr1, arr2))
print(arr)
print("#####"*20)
arr = np.dstack((arr1, arr2))
print(arr)
print(arr.shape)


[[1 2]
 [3 4]]
####################################################################################################
[[5 6]
 [7 8]]
####################################################################################################
[[1 2 5 6]
 [3 4 7 8]]
####################################################################################################
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
####################################################################################################
[[1 2 5 6]
 [3 4 7 8]]
####################################################################################################
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
####################################################################################################
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [33]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])
new_arr=np.array_split(arr,4)
print(new_arr)
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
print("#####"*20)
x = np.where(arr == 4)
print(x)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
####################################################################################################
(array([1]), array([0]))


In [41]:
arr=np.array([1,4,2,3])
x=np.searchsorted(arr,3)
print(x)
x=np.sort(arr)
print('####'*20)
print(x)

3
################################################################################
[1 2 3 4]


In [44]:
arr = np.array([1, 2, 3, 4])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)
filter_arr = []
for element in arr:
  if element > 2:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[1 3]
[False, False, True, True]
[3 4]


In [57]:
arr = np.array([1, 2, 3, 4])
filter_arr = arr > 2
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)
print(arr * 2)
print((arr * 2) + (arr + 4))

[False False  True  True]
[3 4]
[2 4 6 8]
[ 7 10 13 16]


In [55]:
from numpy import random
x = random.randint(50)
print(x)
x = random.rand()
print(x)
x=random.randint(50, size=(5,2))
print(x)
x = random.choice([1,2,3,4,5],size=(5,2))
print(x)

25
0.011044001795179392
[[48 14]
 [18 49]
 [19 40]
 [10 19]
 [16 29]]
[[5 2]
 [1 1]
 [3 1]
 [1 3]
 [2 5]]
